[setup]
rootname = "FERMI"
beamline = "FERMI1"
lambda0 = 2.6e-7
gamma0 = 2739.7
delz = 0.1
shotnoise = 1
one4one = true

[time]
slen = 0.00012
sample = 1

[profile_gauss]
label = "prof2"
c0 = 210130000.0
s0 = 6e-5
sig = 1.77e-5

[field]
power = 0
dgrid = 0.0005
ngrid = 301
waist_size = 0.0001

[beam]
betax = 5.7755
alphax = -1.00786
betay = 19.74
alphay = 1.08443
current = 700
delgam = 0.294
ex = 1e-6
ey = 1e-6

[track]

[sort]

[alter_setup]
beamline = "FERMI3"
harmonic = 50
delz = 0.035
resample = true

[line]
FERMI1 = [ "MOD1", "D1", "C1", "D2", "QF1", "DRAD", "QD1", "DRAD", "QF2", "DRAD", "D3", "QD2", "D4", "C2", "D5", "QF3", "D6",]
FERMI2 = [ "MOD2", "D7", "C3", "D8", "QD3", "D9",]
FERMI3 = [ "RAD", "DD1", "QF4", "DD2", "RAD", "DD1", "QD4", "DD2", "RAD", "DD1", "QF5", "DD2", "RAD", "DD1", "QD5", "DD2", "RAD", "DD1", "QF6", "DD2", "RAD",]
FERMI = [ "FERMI1", "FERMI2", "FERMI3",]

[undulator.MOD1]
lambdau = 0.1
nwig = 30
aw = 6.167

[undulator.MOD2]
lambdau = 0.113
nwig = 13
aw = 5.7915

[undulator.RAD]
lambdau = 0.035
nwig = 69
aw = 1.109
helical = true

[drift.D1]
l = 0.24

[drift.D2]
l = 0.3

[drift.DRAD]
l = 3.56

[drift.D3]
l = 0.02

[drift.D4]
l = 0.27

[drift.D5]
l = 0.35

[drift.D6]
l = 1.05

[drift.D7]
l = 0.706

[drift.D8]
l = 0.32

[drift.D9]
l = 0.6425

[drift.DD1]
l = 0.55

[drift.DD2]
l = 0.605

[quadrupole.QF1]
l = 0.16
k1 = 1.5

[quadrupole.QD1]
l = 0.16
k1 = -1.5

[quadrupole.QF2]
l = 0.16
k1 = 1.1

[quadrupole.QD2]
l = 0.16
k1 = -1.5

[quadrupole.QF3]
l = 0.16
k1 = 1.7

[quadrupole.QD3]
l = 0.16
k1 = -1.55

[quadrupole.QF4]
l = 0.16
k1 = 1.5

[quadrupole.QD4]
l = 0.16
k1 = -1.5

[quadrupole.QF5]
l = 0.16
k1 = 1.5

[quadrupole.QD5]
l = 0.16
k1 = -1.5

[quadrupole.QF6]
l = 0.16
k1 = 1.5

[chicane.C1]
l = 0.7
lb = 0.175
ld = 0.0
delay = 0.0

[chicane.C2]
l = 1.5
lb = 0.375
ld = 0.0
delay = 0.00105

[chicane.C3]
l = 0.7
lb = 0.175
ld = 0.0
delay = 3.76e-5

[marker.M]
dumpbeam = 1

